# This is a config for E2B sandbox template.
# You can use template ID (rbl0xmv9pxvcfcuswegx) or template name (adorable-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("adorable-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("adorable-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('adorable-nextjs-test')

team_id = "170d30bd-6426-4647-a01a-7e86f8994509"
dockerfile = "e2b.Dockerfile"
template_name = "adorable-nextjs-test"
template_id = "rbl0xmv9pxvcfcuswegx"
