# This is a config for E2B sandbox template.
# You can use template ID (rbl0xmv9pxvcfcuswegx) or template name (adorable-nextjs-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("adorable-nextjs-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("adorable-nextjs-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('adorable-nextjs-2')

team_id = "170d30bd-6426-4647-a01a-7e86f8994509"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "adorable-nextjs-2"
template_id = "rbl0xmv9pxvcfcuswegx"
